### ISSUE TITLE
v3.0.1 introduces breaking change: no longer can be used in CJS

### ISSUE THREAD

**Issue by dylang** [sindresorhus/vaca#4]
Hi again!

Your change for my [previous ticket](https://github.com/sindresorhus/vaca/issues/3) broke support for using vaca in CJS packages. I don't think that was intentional, as it wasn't a major bunmp.

Could we add `"main": "./main.js"` to the package.json?

Or an `exports` that supports both `import` and `require`?

**Comment by sindresorhus** [comment]
It was never documented as being available as an API. It was just accidentally available because of the looseness of CJS.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/vaca/releases/tag/v3.0.2
